#!/bin/sh -u

PROCESS=$1

# プロセス ID を切り取る
PRS=`ps -e | grep "$PROCESS"`

if [ $PRS -z ]; then
    echo "No such process."
    exit 1
else
    echo "${PRS}\nKill these processes? [Y/n]"
    read ANS
    case $ANS in
        "" | "Y" | "y" | "yes" | "Yes" | "YES" )
            killall $PROCESS
            echo "Killed!" ;;
        * )
            echo "Canceled." ;;
    esac
    exit 0
fi
