#!/bin/bash

ARG=$1

# Extensions of target files.
targets=(
    *.dvi
    *.aux
    *.log
    *.out
    *.nav
    *.toc
    *.snm
    *.vrb
    *.loa
    texput*
    *.fdb_latexmk
    *.fls
    *.gz
)

# Help.
function usage {
    cat <<EOF
Usage:
    texrm [<options>]

Options:
    -a, --all    : Remove all files under home directory.
    -y, --yes    : Not ask whether to remove.
    -e, --except : Exclude some files by extension.
    -v, --version: TeXrm version.
    -h, --help   : Help for TeXrm.
EOF
}

function fsort {
org_ifs=$IFS # Define the delimiter temporarily.
IFS=$'\n'
files=($(echo "${files[*]}" | sort -n)) # Sort array of files for lex-order.
IFS=$org_ifs
}

# Function to ask remove or not.
function askremove {
    for j in ${files[@]}; do # Indicate target files.
        echo "${j}"
    done
    echo "Remove these files? [Y/n]"
    read ANS
    case $ANS in
        "" | Y | y | yes | Yes | YES )
            for i in ${files[@]}; do
                rm -rf "${i}"
            done
            echo "Removed!" ;;
        * )
            echo "Canceled." ;;
    esac
    exit 0
}

# Make array of target files.
files=()


for i in ${targets[@]}; do
    case $ARG in
        -a | --all )
            files+=(`find ./ -name "${i}"`) ;; # All files under current directory.
        * )
            files+=(`find -maxdepth 1 -name "${i}"`) ;; # Only current directory.
    esac
done

# Execute.
case $ARG in
    -h | --help )
        usage
        exit 0 ;;
    -v | --version )
        echo "TeXrm: Version 1.0.0"
        exit 0 ;;
    * )
        if [ "${#files[@]}" -eq 0 ]; # Check; files exist or not.
        then
            echo "No such files."
            exit 0
        else
            case $ARG in
                "" | -a | --all )
                    fsort
                    askremove 
                    exit 0 ;;
                -Y | -y | -yes | -Yes | -YES ) # Not ask to remove or not
                    fsort
                    for j in ${files[@]}; do
                        echo "${j}"
                    done
                    for i in ${files[@]}; do
                        rm -rf "${i}"
                    done
                    echo "These files have been Removed!"
                    exit 0 ;;
                -e | --except ) # Specify extension don't remove.
                    echo "Please enter the extension to exclude."
                    read EXT
                    files=()
                    for i in ${targets[@]}; do
                        if [[ $i != *.$EXT ]]; then
                            files+=(`find -maxdepth 1 -name "${i}"`)
                        else
                            :
                        fi
                    done
                    fsort
                    askremove
                    exit 0 ;;
                * )
                    echo "TeXrm: Error; Bad Option." 1>&2
                    echo ""
                    echo "Use:"
                    echo "    texrm -h"
                    exit 1
            esac
        fi
esac
